"""LLM-powered adapter scaffolding (stub).

Future capability: given an unknown model architecture, use an LLM
(Claude/GPT) to analyze the model's module tree and config, then
generate a draft ArchitectureAdapter implementation.

This is a strategic stub — the actual implementation depends on:
  1. Having API access to a capable code-generation model
  2. Defining a reliable adapter test harness
  3. Building a prompt template with existing adapters as examples
"""

from __future__ import annotations

import logging
from typing import Optional

_log = logging.getLogger(__name__)


def generate_adapter_draft(
    model_id: str,
    *,
    output_path: Optional[str] = None,
    llm_provider: str = "claude",
) -> str:
    """Generate a draft adapter for an unsupported architecture.

    Returns the generated Python source code as a string.
    Currently a stub that returns a template with TODOs.
    """
    _log.info(
        "adapter generation requested for %s (provider=%s) — returning template",
        model_id, llm_provider,
    )

    # In the future, this will:
    # 1. Load the model config from HuggingFace
    # 2. Inspect the model's module tree (without weights)
    # 3. Identify MLP structure (gate/up/down, fc1/fc2, etc.)
    # 4. Generate adapter code using an LLM
    # 5. Optionally run validation tests

    template = f'''"""Auto-generated adapter draft for {model_id}.

Generated by Dystrio adapter scaffolding. Requires manual review and testing.
"""

from __future__ import annotations
from typing import Any, Dict, List, Sequence

import torch

from .base import ArchitectureAdapter
from .descriptor import OptimizationTarget


class GeneratedAdapter(ArchitectureAdapter):
    """Draft adapter for {model_id}. NEEDS REVIEW."""

    def supported_targets(self) -> List[OptimizationTarget]:
        return [OptimizationTarget.MLP_BLOCK]

    def get_num_layers(self, model) -> int:
        return model.config.num_hidden_layers  # TODO: verify

    def get_mlp(self, model, layer_idx: int):
        return model.model.layers[layer_idx].mlp  # TODO: verify path

    def get_ffn_size(self, model, layer_idx: int) -> int:
        mlp = self.get_mlp(model, layer_idx)
        # TODO: identify the correct projection attribute
        raise NotImplementedError("Needs manual inspection")

    def compress_layer(self, model, layer_idx, kept_idx, dtype, device):
        raise NotImplementedError("TODO: implement compression")

    def collect_block_geometry(self, model, tokenizer, layer_idx, texts,
                               max_len, device, block_size=128, max_tokens=30_000):
        raise NotImplementedError("TODO: implement calibration")

    def collect_block_sensitivity(self, model, tokenizer, layer_idx, texts,
                                   max_len, device, block_size=128, max_tokens=30_000):
        raise NotImplementedError("TODO: implement sensitivity")

    def collect_importance(self, model, tokenizer, layer_idx, texts, max_len, device):
        raise NotImplementedError("TODO: implement importance")

    def snapshot_trainable(self, model, layers):
        raise NotImplementedError("TODO: implement snapshot")

    def restore_trainable(self, model, layers, snap):
        raise NotImplementedError("TODO: implement restore")

    def get_trainable_params(self, model, layers):
        raise NotImplementedError("TODO: implement trainable params")
'''

    if output_path:
        from pathlib import Path
        Path(output_path).write_text(template)
        _log.info("wrote adapter draft to %s", output_path)

    return template
